In [316]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [319]:
x=np.ones(3) # Array of ones value using (ones) function in numpy using one dimentional

### Numpy provide function called ones to fill any array size by ones value
##### we can create an array with one dimention by pass only the number of elements (n) in array like above np.ones(n)
##### or two dimentional by pass number of rows (n) and number of coloumn (m) as follow , np.ones((n,m))
##### or three dimentional by pass number of dimentional (d) then number of rows (n) and then number of coloumns (m), np.ones((d,n,m))

## Q#2: Create y array with elements equal to 0.

In [323]:
y=np.zeros(3)  # Array of zeros value using (zeros) function in numpy using one dimentional 

### Numpy provide function also called zeros to fill any array size by zeros value 
##### we can create an array with one dimention by pass only the number of elements (n) in array like above np.zeros(n)
##### or two dimentional by pass number of rows (n) and number of coloumn (m) as follow , np.zeros([n,m])
##### or three dimentional by pass number of dimentional (d) then number of rows (n) and then number of coloumns (m), np.zeros([d,n,m])

## Q#3: Add x and y arrays.

In [327]:
x+y #summ of two arrays

array([1., 1., 1.])

##### Addition in array is different from list , when adding two arrays its mean to add each elemant in array x with its corresponding in array y
##### one important thing to mention is the two arrays have to be in the same shape in order to perfume addition or at least be comatable in somehow to do addition like (1,3) can be added to (2,1) to generate an array of shape (2,3)

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [331]:
x.ndim #return dimension

1

##### To show dimension of an array , numpy provide quick function called ndim that return how many dimensions this array is.

In [334]:
x.shape #return shape of array 

(3,)

##### To show shape of an array , numpy provide quick function called shape that return how many rows and coloumns in certin array.

In [337]:
x.size  #return number of elements 

3

##### To show size of an array , numpy provide quick function called size that return how many elements are there in certin array.

In [340]:
type(x) #return the data type of an array 

numpy.ndarray

##### To show the type of an array , numpy provide quick function called type refer to data type of an object that return the type of certin object.

## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [344]:
w=np.array([[11,12],[13,14],[15,16]]) # create array using nested lists

##### In order to make more than one dimentional array we will define a function called arraythat recognise the  nested lists . Each inner list corresponds to a row in the 2D array.

## Q#6: Create z array contains the numbers from 1 to 3.

In [348]:
z=np.arange(1,4) # one dimentional array start from 1 and stop before 4 

##### In order to specify an array with specific range we could use arange function that take three parameter (start,stop,step) and notice that top number is execluded in the given array . 
##### Also there is a function called linspace that return a range and take three parameter same as arange but different in the step parameter ; instead of step parameter is how many values we want to generate parameter (start,end,no of values)

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [352]:
z=z.reshape((3,1)) #reshape z
newArray=np.hstack((w,z))  #combine the two arrays

##### there are different functions that do combine between arrays like concatenate , hstack , and vstack 
##### concatenate is take the two arrays to be combined and the axis ((array1,array2),axis=0) if axis =0 then it means for rows and if it 1 it is for coloumn 
##### hstack will give a new dimension hortizinal of the two arrays (array1,array2)
##### vstack will give a new dimension vertical of the two arrays (array1,array2)
##### before doing combination horizontally, we need to make sure that z has the same number of rows as w. Since w has 3 rows and z will contain the numbers from 1 to 3 (a 1D array), we need to reshape z into a column (2D array with 3 rows and 1 column) before horizontally stacking them.

## Q#8: Print all elements of "newArray" using the loop.

In [356]:
# Loop through all elements and print them
for row in newArray:
    for element in row:
        print (element)
    

11
12
1
13
14
2
15
16
3


##### We have used nested for loop to reach each element in the matrix 

## Q#9: Reverse the columns and rows of "newArray".

In [358]:
newArray=newArray.T # rwos will be coloumns and coloumns will be rwos 

## Q#10: Decrement all elements of "newArray" with 1.

In [360]:
newArray=newArray-1
print(newArray)

[[10 12 14]
 [11 13 15]
 [ 0  1  2]]


## Q#11: Find smallest and biggest values in "newArray".

In [393]:
newArray.max() # use max to bring highest value in array 

15

##### using max one of aggregation function that can be performed in Row data and return the highest value in array 

## Q#12: Print the first row of "newArray" using indexing.

In [366]:
print(newArray[0,:]) # bring in the first row which its index is 0 and all elements in that rwo so use colon :

[10 12 14]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [370]:
print(newArray[0,1])

12


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [374]:
print(newArray[2,0]) #access value element by typing its rwo index , coloumn index
print(newArray[1,1])

0
13


## Q#15: Change the shape of "newArray" to (9,1).

In [391]:
newArray=newArray.reshape((9,1)) # reshape into 9 rwos and 1 coloumn

## Q#16: Change the shape of "newArray" to (3,2).

In [398]:
# attempts to reshape it into a 3x2 array (3 rows, 2 columns), 
#this will cause error because the total number of elements (9) 
#cannot be reshaped into a 3x2 array (which requires only 6 elements).

# Well Done 🎉